---
- name: Run Docker container from built image
  hosts: localhost
  become: true

  tasks:
    - name: Ensure Docker container is running
      community.docker.docker_container:
        name: retail-web
        image: abc-retail-app
        state: started
        restart_policy: always
        published_ports:
          - "9090:8080"
